@api_url = https://api.themoviedb.org/3/movie/popular?language=es&page=1&api_key=1b501bbda107113acc653f328a2e935d
https://api.themoviedb.org/3/movies/popular?page=1&language=en&api_key=1b501bbda107113acc653f328a2e935d
@genres_url =https://api.themoviedb.org/3/genre/tv/list?api_key=1b501bbda107113acc653f328a2e935d
###
GET {{api_url}}

###
GET {{genres_url}}

@images_url = https://api.themoviedb.org/3/movie/539972/images?api_key=1b501bbda107113acc653f328a2e935d
###

###
GET {{images_url}}

###
GET  https://api.themoviedb.org/3/configuration/languages?api_key=1b501bbda107113acc653f328a2e935d