@api_url = https://api.themoviedb.org/3/movie/popular?language=es&page=1&api_key=your_api_key_here

@genres_url =https://api.themoviedb.org/3/genre/tv/list?api_key=your_api_key_here

###
GET {{api_url}}

###
GET {{genres_url}}

@images_url = https://api.themoviedb.org/3/movie/539972/images?api_key=your_api_key_here


###
GET {{images_url}}

###
GET  https://api.themoviedb.org/3/configuration/languages?api_key=your_api_key_here